### ISSUE TITLE
Next steps.

### ISSUE THREAD

**Issue by SenHeng** [SenHeng/TheExpense#16]
# Plans

## Make better use of GitHub features

Currently, project management is handled via Trello. I'd like to move that into issues to make use of labels and milestones. Design docs and specs should be moved into either the wiki or written in the `docs` folder.
reference: https://github.com/Microsoft/vscode/milestones

## Decide the end goal

Initial goal was simply, 

> digitise expenses so my accountant will give me a discount.

Next goal should probably be a little more *ambitious*.

## Prepare next steps

Once end goal is decided, break down the steps needed to get from here to there, then work on it.

## TODO

- [ ] move Trello tasks into issues
- [ ] move documentation and specs into either wiki or docs
- [ ] decide the end goal for this project
- [ ] split goals into tasks
